stages:
  - build_and_deploy

build a jar and deploy to docker hub:
  stage: build_and_deploy
  image: openjdk:12-alpine
  script:
    - ./mvnw clean package -Dmaven.test.skip=true docker:build docker:push
  only:
    - master
